name: re_sew
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^0.3.0
  flutter_staggered_grid_view:
  flutter_launcher_icons:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/img/Re-Sew_Icon.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  assets:
    - assets/img/denim_apron.png
    - assets/img/Clothing.jpg
    - assets/img/Home.jpg
    - assets/img/Luggage.jpg
    - assets/img/Other.jpg
    - assets/img/Cushion.png
    - assets/img/jeans.jpg
    - assets/img/washbag.jpg
    - assets/img/Cotton.png
    - assets/img/Polyester.jpg
    - assets/img/Wool.jpg
    - assets/img/Denim.jpg
    - assets/img/Learning_To_Sew.jpg
    - assets/img/HandSew.jpg
    - assets/img/Master.jpg
    - assets/img/Medium.jpg
    - assets/img/Sewing_Machine.jpg
    - assets/img/Long.jpg
    - assets/img/Sewing_dark.jpg
    - assets/img/Pink_fabric.jpg
    - assets/img/spools.jpg
    - assets/img/Apron/ApronStep1.jpg
    - assets/img/Apron/ApronStep2.jpg
    - assets/img/Apron/ApronStep3.jpg
    - assets/img/Apron/ApronStep4.jpg
    - assets/img/Apron/ApronStep5.jpg
    - assets/img/Apron/ApronStep6.jpg
    - assets/img/Apron/ApronStep7.jpg
    - assets/img/Apron/ApronStep8.jpg
    - assets/img/Apron/ApronStep9.jpg
    - assets/img/Apron/ApronStep10.jpg
    - assets/img/JeanRepair/JeanRepairStep1.jpg
    - assets/img/JeanRepair/JeanRepairStep2.jpg
    - assets/img/JeanRepair/JeanRepairStep3.jpg
    - assets/img/JeanRepair/JeanRepairStep4.jpg
    - assets/img/JeanRepair/JeanRepairStep5.jpg
    - assets/img/JeanRepair/JeanRepairStep6.jpg
    - assets/img/JeanRepair/JeanRepairStep7.jpg
    - assets/img/JeanRepair/JeanRepairStep8.jpg
    - assets/img/JeanRepair/JeanRepairStep9.jpg
    - assets/img/JeanRepair/JeanRepairStep10.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade1.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade2.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade3.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade4.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade5.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade6.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade7.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade8.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade9.jpg
    - assets/img/ClothingUpgrade/ClothingUpgrade10.jpg
    - assets/img/Nathaniel.png
    - assets/img/ToteBag/ToteStep1.jpg
    - assets/img/ToteBag/ToteStep2.jpg
    - assets/img/ToteBag/ToteStep3.jpg
    - assets/img/ToteBag/ToteStep4.jpg
    - assets/img/ToteBag/ToteStep5.jpg
    - assets/img/ToteBag/ToteStep6.jpg
    - assets/img/ToteBag/ToteStep7.jpg
    - assets/img/ToteBag/ToteStep8.jpg
    - assets/img/ToteBag/ToteStep9.jpg
    - assets/img/ToteBag/ToteStep10.jpg
    - assets/img/WashBag/Washbag1.jpg
    - assets/img/WashBag/Washbag2.jpg
    - assets/img/WashBag/Washbag3.jpg
    - assets/img/WashBag/Washbag4.jpg
    - assets/img/WashBag/Washbag5.jpg
    - assets/img/WashBag/Washbag6.jpg
    - assets/img/WashBag/Washbag7.jpg
    - assets/img/WashBag/Washbag8.jpg
    - assets/img/WashBag/Washbag9.jpg
    - assets/img/WashBag/Washbag10.jpg
    - assets/img/WashBag/Washbag11.jpg
    - assets/img/Cushion/Cushion1.jpg
    - assets/img/Cushion/Cushion2.jpg
    - assets/img/Cushion/Cushion3.jpg
    - assets/img/Cushion/Cushion4.jpg
    - assets/img/Cushion/Cushion5.jpg
    - assets/img/Cushion/Cushion6.jpg
    - assets/img/Cushion/Cushion7.png
    - assets/img/Cushion/Cushion8.jpg
    - assets/img/Cushion/Cushion9.jpg
    - assets/img/Cushion/Cushion10.jpg
    - assets/img/Quality.jpg
    - assets/img/Swap.jpg
    - assets/img/Boro.jpg
    - assets/img/Upcycle.jpg
    - assets/img/ToteBag/ToteBag.png
    - assets/img/ToteBag/Tote.jpg
    - assets/img/JeanRepair/BoroJean.jpg
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
